services:
  discodrome:
    image: snotfishspam/discodrome:latest
    container_name: discodromev2
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SUBSONIC_SERVER=${SUBSONIC_SERVER}
      - SUBSONIC_USER=${SUBSONIC_USER}
      - SUBSONIC_PASSWORD=${SUBSONIC_PASSWORD}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_TEST_GUILD=${DISCORD_TEST_GUILD}
      - DISCORD_OWNER_ID=${DISCORD_OWNER_ID}
      - BOT_STATUS=${BOT_STATUS}
    volumes:
    - ./data/guilds.db:/app/guilds.db
